export const categories = [
  { value: "-Other-", label: "-Other-" },
  { value: "Technology", label: "Technology" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Artificial Intelligence", label: "Artificial Intelligence" },
  { value: "Data Science", label: "Data Science" },
  { value: "Web Development", label: "Web Development" },
  { value: "Mobile Apps", label: "Mobile Apps" },
  { value: "Cybersecurity", label: "Cybersecurity" },
  { value: "Cloud Computing", label: "Cloud Computing" },
  { value: "Programming", label: "Programming" },
  { value: "Startups", label: "Startups" },
  { value: "Entrepreneurship", label: "Entrepreneurship" },
  { value: "Finance", label: "Finance" },
  { value: "Cryptocurrency", label: "Cryptocurrency" },
  { value: "Health", label: "Health" },
  { value: "Fitness", label: "Fitness" },
  { value: "Travel", label: "Travel" },
  { value: "Food", label: "Food" },
  { value: "Sports", label: "Sports" },
  { value: "Photography", label: "Photography" },
];
